### ISSUE TITLE
A big long list of problematic things

### ISSUE THREAD

**Issue by awonnacott** [casey-chow/tigertrade#169]
Feel free to add to this list:

- [x] Resizing the window should update the left offset of the listings/seeks cards so they don't get off-center (something in #214)
- [x] On small screens, left nav bar should not dock and should just be pullable from the side (fixed: 3ea1acc)
- [x] Scrolling unselects items in UI #196
- [x] Filter bar should resize when the nav bar opens and closes
- ~[Hide Navigation Bar on Scroll Down](https://stackoverflow.com/questions/37395561/how-to-hide-a-mobile-browsers-address-bar) per #191~
- [x] Strange behavior when selecting and then deselecting "Favorites" per #198 (fixed: #200)
- ~Clicking grey background should close open listing/seek card per #139~
- [x] Clicking My listings or My seeks when not logged in doesn't redirect to CAS (fixed: b66d3f7)
